#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(
    cd "$(dirname "${BASH_SOURCE[0]}")"
    pwd -P
)"

cd "$SCRIPT_DIR/.."
if ! npm run lint; then
    echo "ERROR: Lint failed." >&2
    exit 1
fi

if ! npm run test; then
    echo "ERROR: Tests failed." >&2
    exit 1
fi
